services:
  # Static site service for the Next.js frontend
  - type: web
    name: epicquest-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://epicquest-backend.onrender.com
      - key: NODE_VERSION
        value: 18.x

  # Backend API service (reference only - should be deployed separately)
  # - type: web
  #   name: epicquest-backend
  #   env: node
  #   plan: starter
  #   buildCommand: npm install && npm run build
  #   startCommand: npm run start:prod
  #   healthCheckPath: /health
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: epicquest-db
  #         property: connectionString
  #     - key: JWT_SECRET
  #       sync: false
  #     - key: AMADEUS_API_KEY
  #       sync: false
  #     - key: AMADEUS_API_SECRET
  #       sync: false
  #     - key: HOTELBEDS_API_KEY
  #       sync: false
  #     - key: HOTELBEDS_API_SECRET
  #       sync: false
  #     - key: ADYEN_API_KEY
  #       sync: false
  #     - key: ADYEN_MERCHANT_ACCOUNT
  #       sync: false

# databases:
#   - name: epicquest-db
#     plan: starter
#     ipAllowList: []